-- Pop Talk DW MVP: Databricks Silver JSONL -> Snowflake staging
-- Run with role POP_TALK_DW_DEV_ROLE and warehouse POP_TALK_DW_WH.

USE ROLE POP_TALK_DW_DEV_ROLE;
USE WAREHOUSE POP_TALK_DW_WH;
USE DATABASE POP_TALK_DW_DEV;
USE SCHEMA STAGING;

CREATE FILE FORMAT IF NOT EXISTS JSONL_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = FALSE
    COMPRESSION = AUTO
    COMMENT = 'One JSON object per line from Databricks Silver exports';

CREATE STAGE IF NOT EXISTS MOVIE_SAMPLE_STAGE
    FILE_FORMAT = JSONL_FORMAT
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Manual MVP exchange stage for validated Databricks exports';

-- Upload movies_silver.jsonl to MOVIE_SAMPLE_STAGE before continuing.
LIST @MOVIE_SAMPLE_STAGE;

CREATE TABLE IF NOT EXISTS MOVIES_SILVER_RAW (
    RUN_ID STRING NOT NULL,
    SOURCE_MOVIE_ID NUMBER(38, 0) NOT NULL,
    RECORD_SHA256 STRING NOT NULL,
    PAYLOAD VARIANT NOT NULL,
    SOURCE_FILE STRING NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Validated Databricks Silver movie payloads; one current row per run and source movie';

CREATE OR REPLACE TEMPORARY TABLE INCOMING_MOVIES_SILVER (
    PAYLOAD VARIANT,
    SOURCE_FILE STRING
);

COPY INTO INCOMING_MOVIES_SILVER (PAYLOAD, SOURCE_FILE)
FROM (
    SELECT
        $1,
        METADATA$FILENAME
    FROM @MOVIE_SAMPLE_STAGE
)
FILE_FORMAT = (FORMAT_NAME = JSONL_FORMAT)
PATTERN = '.*movies_silver[.]jsonl'
ON_ERROR = ABORT_STATEMENT;

-- Fail the worksheet manually if these checks do not return 100, 100, 0, 0.
SELECT
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PAYLOAD:source_movie_id::NUMBER) AS DISTINCT_MOVIE_COUNT,
    COUNT_IF(PAYLOAD:run_id::STRING IS NULL) AS MISSING_RUN_ID_COUNT,
    COUNT_IF(PAYLOAD:record_sha256::STRING IS NULL) AS MISSING_HASH_COUNT
FROM INCOMING_MOVIES_SILVER;

MERGE INTO MOVIES_SILVER_RAW AS TARGET
USING (
    SELECT
        PAYLOAD:run_id::STRING AS RUN_ID,
        PAYLOAD:source_movie_id::NUMBER AS SOURCE_MOVIE_ID,
        PAYLOAD:record_sha256::STRING AS RECORD_SHA256,
        PAYLOAD,
        SOURCE_FILE
    FROM INCOMING_MOVIES_SILVER
) AS SOURCE
ON TARGET.RUN_ID = SOURCE.RUN_ID
   AND TARGET.SOURCE_MOVIE_ID = SOURCE.SOURCE_MOVIE_ID
WHEN MATCHED AND TARGET.RECORD_SHA256 <> SOURCE.RECORD_SHA256 THEN
    UPDATE SET
        TARGET.RECORD_SHA256 = SOURCE.RECORD_SHA256,
        TARGET.PAYLOAD = SOURCE.PAYLOAD,
        TARGET.SOURCE_FILE = SOURCE.SOURCE_FILE,
        TARGET.LOADED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        RUN_ID,
        SOURCE_MOVIE_ID,
        RECORD_SHA256,
        PAYLOAD,
        SOURCE_FILE,
        LOADED_AT
    )
    VALUES (
        SOURCE.RUN_ID,
        SOURCE.SOURCE_MOVIE_ID,
        SOURCE.RECORD_SHA256,
        SOURCE.PAYLOAD,
        SOURCE.SOURCE_FILE,
        CURRENT_TIMESTAMP()
    );

SELECT
    RUN_ID,
    COUNT(*) AS MOVIE_COUNT,
    COUNT(DISTINCT SOURCE_MOVIE_ID) AS DISTINCT_MOVIE_COUNT,
    COUNT_IF(PAYLOAD:title_ko::STRING IS NULL) AS MISSING_TITLE_COUNT,
    COUNT_IF(PAYLOAD:release_date::DATE IS NULL) AS MISSING_RELEASE_DATE_COUNT,
    MIN(PAYLOAD:release_date::DATE) AS MINIMUM_RELEASE_DATE,
    MAX(PAYLOAD:release_date::DATE) AS MAXIMUM_RELEASE_DATE
FROM MOVIES_SILVER_RAW
WHERE RUN_ID = 'movie-sample-20260909T003725Z'
GROUP BY RUN_ID;

ALTER WAREHOUSE POP_TALK_DW_WH SUSPEND;
