services:
  airflow-init:
    networks:
    - default
    - application
    environment:
      POP_TALK_POSTGRES_HOST: pop-talk-service-db
      POP_TALK_POSTGRES_PORT: '5432'
  airflow-apiserver:
    networks:
    - default
    - application
    environment:
      POP_TALK_POSTGRES_HOST: pop-talk-service-db
      POP_TALK_POSTGRES_PORT: '5432'
  airflow-scheduler:
    networks:
    - default
    - application
    environment:
      POP_TALK_POSTGRES_HOST: pop-talk-service-db
      POP_TALK_POSTGRES_PORT: '5432'
  airflow-dag-processor:
    networks:
    - default
    - application
    environment:
      POP_TALK_POSTGRES_HOST: pop-talk-service-db
      POP_TALK_POSTGRES_PORT: '5432'
  airflow-triggerer:
    networks:
    - default
    - application
    environment:
      POP_TALK_POSTGRES_HOST: pop-talk-service-db
      POP_TALK_POSTGRES_PORT: '5432'
networks:
  application:
    external: true
    name: ${APPLICATION_NETWORK:-pop-talk-application_default}
