select
    o.source_run_id || '|' || o.artifact_version || '|' || o.canonical_movie_key as observation_key,
    o.source_run_id, o.artifact_version, p.publication_revision,
    p.exchange_ready_key, p.completed_at as publication_completed_at,
    o.canonical_movie_key, o.source_observed_at, o.record_sha256, o.loaded_at,
    nullif(trim(o.payload:kofic_movie_cd::string), '') as kofic_movie_cd,
    nullif(trim(o.payload:kmdb_id::string), '') as kmdb_id,
    o.payload:kmdb_matched::boolean as kmdb_matched,
    nullif(trim(o.payload:kmdb_mapping_status::string), '') as kmdb_mapping_status,
    nullif(trim(o.payload:provisional_kmdb_id::string), '') as provisional_kmdb_id,
    o.payload:kmdb_candidate_count::integer as kmdb_candidate_count,
    o.payload:kmdb_candidates_truncated::boolean as kmdb_candidates_truncated,
    o.payload:kmdb_candidates_ambiguous::boolean as kmdb_candidates_ambiguous,
    nullif(trim(o.payload:title_ko::string), '') as title_ko,
    nullif(trim(o.payload:title_en::string), '') as title_en,
    nullif(trim(o.payload:title_original::string), '') as title_original,
    try_to_date(o.payload:release_date::string) as release_date,
    o.payload:production_year::integer as production_year,
    o.payload:runtime_minutes::integer as runtime_minutes,
    nullif(trim(o.payload:movie_type::string), '') as movie_type,
    nullif(trim(o.payload:production_status::string), '') as production_status,
    o.payload:countries as countries, o.payload:genres as genres,
    o.payload:directors as directors, o.payload:director_names_en as director_names_en,
    o.payload:actors as actors, o.payload:actor_roles as actor_roles,
    o.payload:production_companies as production_companies,
    nullif(trim(o.payload:viewing_grade::string), '') as viewing_grade,
    nullif(trim(o.payload:poster_url::string), '') as poster_url,
    nullif(trim(o.payload:plot::string), '') as plot,
    o.payload:policy_eligible::boolean as policy_eligible,
    o.payload:policy_exclusion_reasons as policy_exclusion_reasons,
    nullif(trim(o.payload:policy_version::string), '') as policy_version,
    nullif(trim(o.payload:ingestion_source::string), '') as ingestion_source,
    nullif(trim(o.payload:source_object_key::string), '') as source_object_key,
    o.payload:content_sha256::string as content_sha256,
    o.payload:policy_sha256::string as policy_sha256,
    o.payload:matching_sha256::string as matching_sha256
from {{ source('pop_talk_staging', 'movie_observations_raw') }} o
join {{ ref('stg_successful_exchange_publications') }} p
  on o.source_run_id = p.source_run_id and o.artifact_version = p.artifact_version
