"""실제 PostgreSQL의 격리 스키마에서 ID·운영 정보 보존, 롤백, 재시도를 검증한다."""
import os
import unittest
import uuid
from datetime import datetime, timezone, timedelta

import psycopg
from pipelines.orchestration.service_sync import sync_service


class ScopedConnection:
    def __init__(self, connection, schema):
        self.connection, self.schema = connection, schema
    def __getattr__(self, name):
        return getattr(self.connection, name)
    def execute(self, query, *args):
        return self.connection.execute(query.replace("search_path TO dev,", f"search_path TO {self.schema},"), *args)


@unittest.skipUnless(os.environ.get("RUN_SERVICE_POSTGRES_TESTS") == "1", "격리 PostgreSQL 통합 테스트")
class ServiceSyncTests(unittest.TestCase):
    def setUp(self):
        self.db = psycopg.connect(host=os.environ['POP_TALK_POSTGRES_HOST'], port=os.environ.get('POP_TALK_POSTGRES_PORT','5432'),
            dbname=os.environ['POP_TALK_POSTGRES_DB'], user=os.environ['POP_TALK_POSTGRES_USER'],
            password=os.environ['POP_TALK_POSTGRES_PASSWORD'], autocommit=True)
        self.schema = "test_direct_" + uuid.uuid4().hex
        self.db.execute(f"CREATE SCHEMA {self.schema}")
        self.db.execute(f"SET search_path TO {self.schema},public,cdb_admin")
        for table in ('popcorn_movies','batch_runs','movie_boxoffice_daily','movie_editorial','popcorn_movie_embeddings','movie_embedding_jobs'):
            self.db.execute(f"CREATE TABLE {table} (LIKE dev.{table} INCLUDING ALL)")
            if table not in ('movie_boxoffice_daily','movie_editorial'):
                self.db.execute(f"ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT")
                self.db.execute(f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
        # 실제 서비스 트리거를 격리 스키마에 복제해 부수 효과도 검증한다.
        for name in ('queue_movie_embedding','protect_removed_movie','set_updated_at'):
            definition=self.db.execute("SELECT pg_get_functiondef(%s::regprocedure)",(f'dev.{name}()',)).fetchone()[0]
            self.db.execute(definition.replace('dev.',self.schema+'.').replace("TO 'dev'",f"TO '{self.schema}'"))
        triggers=self.db.execute("SELECT pg_get_triggerdef(oid) FROM pg_trigger WHERE tgrelid='dev.popcorn_movies'::regclass AND NOT tgisinternal").fetchall()
        for definition, in triggers:
            self.db.execute(definition.replace('dev.',self.schema+'.'))
        self.connection=ScopedConnection(self.db,self.schema)
        self.cutoff=datetime(2026,9,11,tzinfo=timezone.utc)
        self.db.execute("""INSERT INTO popcorn_movies(kofic_movie_cd,title_ko,release_date,plot,kmdb_id,kmdb_matched,
            service_status,approval_status,approved_at,source_hash) VALUES('1','기존','2020-01-01','보존할 상세','K1',true,'PUBLISHED','APPROVED',now(),%s)""",('a'*64,))
        self.db.execute("INSERT INTO movie_editorial(movie_id,plot_override) VALUES(1,'운영자 보정')")

    def tearDown(self):
        self.db.execute('SET search_path TO public')
        assert self.schema.startswith('test_direct_') and len(self.schema)==44
        self.db.execute(f"DROP SCHEMA {self.schema} CASCADE")
        self.db.close()

    def movie(self, code, **updates):
        return {'KOFIC_MOVIE_CD':code,'TITLE_KO':'새 제목','RELEASE_DATE':'2020-01-01',
                'POLICY_ELIGIBLE':True,'GENRES':'["드라마"]',**updates}

    def sync(self, movies, facts=(), days=0):
        return sync_service(self.connection,movies,list(facts),cutoff=self.cutoff+timedelta(days=days),run_id='test-run',model_version='b'*64)

    def test_upsert_preserves_id_editorial_approval_and_missing_details(self):
        result=self.sync([self.movie('1'),self.movie('2'),self.movie('3',POLICY_ELIGIBLE=False)])
        self.assertEqual((result['inserted'],result['updated'],result['skipped']),(1,1,1))
        self.assertEqual(self.db.execute("SELECT id,plot,kmdb_id,kmdb_matched,service_status::text,approval_status::text FROM popcorn_movies WHERE kofic_movie_cd='1'").fetchone(),
                         (1,'보존할 상세','K1',True,'PUBLISHED','APPROVED'))
        self.assertEqual(self.db.execute('SELECT plot_override FROM movie_editorial').fetchone()[0],'운영자 보정')
        self.assertEqual(self.db.execute("SELECT service_status::text,approval_status::text FROM popcorn_movies WHERE kofic_movie_cd='2'").fetchone(),('DRAFT','PENDING'))
        self.assertEqual(self.sync([self.movie('1'),self.movie('2')],days=1)['updated'],0)

    def test_failed_fact_rolls_back_movie_change_and_retry_succeeds(self):
        fact={'KOFIC_MOVIE_CD':'1','TARGET_DATE':'2026-09-10','RANK':-1,'SOURCE_RUN_ID':'source'}
        with self.assertRaises(psycopg.errors.CheckViolation): self.sync([self.movie('1')],[fact])
        self.assertEqual(self.db.execute("SELECT title_ko FROM popcorn_movies WHERE id=1").fetchone()[0],'기존')
        self.assertEqual(self.db.execute("SELECT status::text FROM batch_runs").fetchone()[0],'FAILED')
        fact['RANK']=1
        self.sync([self.movie('1')],[fact])
        self.assertEqual(self.db.execute("SELECT rank,movie_id FROM movie_boxoffice_daily").fetchone(),(1,1))

    def test_stale_run_and_duplicate_retry(self):
        movies=[self.movie('1')]
        first=self.sync(movies,days=1)
        self.assertEqual(self.sync(movies,days=1),first)
        with self.assertRaisesRegex(RuntimeError,'오래된'): self.sync([self.movie('1',TITLE_KO='옛 제목')])
        self.assertEqual(self.db.execute("SELECT title_ko FROM popcorn_movies WHERE id=1").fetchone()[0],'새 제목')


if __name__=='__main__': unittest.main()
