name: pop_talk_dw
version: 1.0.0
config-version: 2

profile: pop_talk_dw

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: target
clean-targets: ["target", "dbt_packages"]

models:
  pop_talk_dw:
    staging:
      +schema: STAGING
      +materialized: view
    dw:
      +schema: DW
      +materialized: table
    mart:
      +schema: MART
      +materialized: view
